INSERT INTO CITY VALUES (1, 'Ankara');
INSERT INTO CITY VALUES (2, 'Istanbul');

INSERT INTO DISTRICT VALUES (1, 'Cankaya', 1);
INSERT INTO DISTRICT VALUES (2, 'Yenimahalle', 1);
INSERT INTO DISTRICT VALUES (3, 'Mamak', 1);


INSERT INTO DISTRICT VALUES (4, 'Kadikoy', 2);
INSERT INTO DISTRICT VALUES (5, 'Sisli', 2);
INSERT INTO DISTRICT VALUES (6, 'Kucukcekmece', 2);





