INSERT INTO CITY VALUES (1, 'Ankara');
INSERT INTO CITY VALUES (2, 'Istanbul');

INSERT INTO DISTRICT VALUES (1, 'Cankaya', 1);
INSERT INTO DISTRICT VALUES (2, 'Yenimahalle', 1);
INSERT INTO DISTRICT VALUES (3, 'Kadıkoy', 2);
INSERT INTO DISTRICT VALUES (4, 'Tuzla', 2);





